apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: bhanuu1903/fastapi3
          ports:
            - containerPort: 8000
          env:
            - name: RAPIDAPI_HOST
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: RAPIDAPI_HOST
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: RAPIDAPI_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: DATABASE_URL
            - name: SMTP_SERVER
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: SMTP_SERVER
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: SMTP_PORT
            - name: EMAIL_SENDER
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: EMAIL_SENDER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: EMAIL_PASSWORD
            - name: EMAIL_RECEIVER
              valueFrom:
                secretKeyRef:
                  name: fastapi-secrets
                  key: EMAIL_RECEIVER

          # Add Liveness and Readiness Probes
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          # Set resource limits (optional but recommended)
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

          # Graceful shutdown settings
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000