name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          cd Frontend/project
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

  deploy:
    name: Deploy Frontend to AKS
    runs-on: ubuntu-latest
    needs: build-and-push  # Only runs if image is pushed successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/frontend-app frontend-app=${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
          kubectl apply -f frontend/project/deployment.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
